# Generated by Django 3.0 on 2021-07-30 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolereq',
            old_name='ud',
            new_name='fud',
        ),
        migrations.AlterField(
            model_name='fitemlist',
            name='fsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FurnitureApp.OnlineFurniture'),
        ),
        migrations.AlterField(
            model_name='onlinefurniture',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolereq',
            name='frpfe',
            field=models.ImageField(default='sofa.jpg', upload_to='Rolereqpics/'),
        ),
    ]
