# Generated by Django 3.0 on 2021-07-30 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureApp', '0002_auto_20210730_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitemlist',
            old_name='fsid',
            new_name='rsid',
        ),
        migrations.AlterField(
            model_name='onlinefurniture',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
